mod_id=styledplayerlist
maven_group=eu.pb4
mod_version=26.2.0
minecraft_version=26.2
neo_version=26.2.0.57
parchment_version=2025.09.14

ltlib_version=[26.2,26.3)
placeholder_api_version=[3.1.0+26.1,4.0)

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
