name: Java CI with Gradle

on:
  push:
  schedule:
    - cron: 0 0 1 * *
jobs:

  jdk21:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Locate built JARfile
        id: jar
        run: echo "##[set-output name=jarfile;]$(find build/libs/ -name "*.jar" -not -name "*slim*" -not -name "*source*")"

      - name: Set Artifact name
        id: jarname
        run: echo "##[set-output name=jarname;]$(find build/libs/ -name "*.jar" -not -name "*slim*" -not -name "*source*" | sed 's:.*/::')"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.jarname.outputs.jarname }}
          path: ${{ steps.jar.outputs.jarfile }}
          retention-days: 90
